---
- name: This Yaml is to Install redis
  hosts: mongodb
  become: true
  vars:
    catalogue_host: catalogue-dev.daws88s.shop
  tasks:
     - name: Enable module redis:7
       ansible.builtin.command: dnf module enable redis:7 -y

     - name: Install Module redis
       ansible.builtin.package:
         name: redis
         state: present

     - name: Replace IP to 0.0.0.0 in file
       ansible.builtin.replace:
         path: /etc/redis.conf
         regexp: '127.0.0.1'
         replace: '0.0.0.0'

     - name: Replace protection mode to no
       ansible.builtin.lineinfile:
         path: /etc/redis.conf
         regexp: '^\s*protected-mode'
         replace: 'protected-mode no'

     -  name: Enable and Start nginx
        ansible.builtin.service:
         name: redis
         enabled: true
         state: started