---
- name: This Yaml is to Install sql database
  hosts: mysql
  become: true  
  tasks:
   - name: Install mysql server
     ansible.builtin.package:
       name: mysql-server
       state: present

   - name: Enable and start mysql mysql-server
     ansible.builtin.service:
        name: mysqld
        enabled: true
        state: started
 
   - name: Reset SQL password
     ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1