---
- name: This Yaml is to Install shipping service
  host: shipping
  become: true  
  vars:
   cart_host: cart-dev.daws88s.shop
   mysql_host: mysql-dev.daws88s.shop
   dbs:
     - /app/db/schema.sql
     - /app/db/app-user.sql 
     - /app/db/master-data.sql
  tasks:
   - name: Install maven 
     ansible.builtin.package:
       name: maven
       state: present
   - name: Create System shipping Roboshop
     ansible.builtin.shipping:
        name: roboshop
        home: /app
        shell: /sbin/nologin
        comment: "roboshop system user"
        system: true
        state: present
    
   - name: Create app directory
     ansible.builtin.file:
          path: /app
          state:  directory
    
   - name: Download package from custom url
     ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip 
        dest: /tmp/shipping.zip 

   - name: Copy shipping service file and replace the variable
     ansible.builtin.template:
        src: shipping.service.j2
        dest: /etc/systemd/system/shipping.service

   - name: reload payment systemd service  
     ansible.builtin.systemd_service:
        name: shipping
        daemon_reload: true
        enabled: true
        state: started

   - name: Install mysql
     ansible.builtin.package:
       name: mysql
       state: present 
  
   - name: Import sql db 
     community.mysql.mysql_db:
      login_host: mysql-dev.daws88s.shop
      login_user: root 
      login_password: RoboShop@1
      state: import
      name: all
      target: "{{ item }}"
     loop: "{{ dbs }}"