---
- name: This Yaml is to Install rabbitmq database
  hosts: rabbitmq
  become: true  
  tasks:
   - name: Install rabbitmq
     ansible.builtin.package:
       name: rabbitmq-server
       state: present

   - name: rabbitmq start and enable service
     ansible.builtin.service:
        name: rabbitmq-server
        enabled: true
        state: started
    
   - name: |-
      Add user to server and assign full access control on / vhost.
      The user might have permission rules for other vhost but you don't care.
     community.rabbitmq.rabbitmq_user:
          user: roboshop
          password: roboshop123
          vhost: /
          configure_priv: .*
          read_priv: .*
          write_priv: .*
          state: present

