---
- name: This Yaml is to Install user service
  hosts: payment
  become: true
  vars:
    cart_host: cart-dev.daws88s.shop
    user_host: user-dev.daws88s.shop
    rabbitmq_host: rabbitmq-dev.daws88s.shop
    package:
      - gcc
      - python3
      - python3-devel
  tasks:
    - name: Install Module nodejs:20
      ansible.builtin.package:
        name: "{{ item }}"
        state: present 
      loop: "{{ package }}"

    - name: Create System payment Roboshop
      ansible.builtin.user:
        name: roboshop
        home: /app
        shell: /sbin/nologin
        comment: "roboshop system user"
        system: true
        state: present
    
    - name: Create app directory
      ansible.builtin.file:
          path: /app
          state:  directory

    - name: Download package from custom url
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/payment-v3.zip 
        dest: /tmp/payment.zip 

    - name: Unzip zip file payment.zip
      ansible.builtin.unarchive:
         src: /tmp/payment.zip
         dest: /app
         remote_src: yes

    - name: Install pip3 dependencies
      ansible.builtin.shell: pip3 install -r requirements.txt
      args:
          chdir: /app
    
    - name: Copy user service file and replace the variable
      ansible.builtin.template:
        src: payment.service.j2
        dest: /etc/systemd/system/payment.service

    - name: reload payment systemd service  
      ansible.builtin.systemd_service:
        name: payment
        daemon_reload: true
        enabled: true
        state: started