---
- name: This Yaml is used to deploy ec2 instances in AWS
  hosts: local
  connection: local
  vars:
    Env: dev
    Project: Roboshop
    Imageid: ami-0220d79f3f480ecf5
    Instance_type: t3.micro
    Securitygrp: devops-sg
    subnetid: subnet-0a76f340dca5f78a5
    zone: daws88s.shop
    Instances: 
       - mongodb
       - catalogue
  tasks:
    - name: Create ec2 instance
      amazon.aws.ec2_instance: 
          name: "{{ item }}-{{ Env }}"
          image_id: "{{ Imageid }}"
          instance_type: "{{ Instance_type }}"
          security_group: "{{ Securitygrp }}"
          vpc_subnet_id: "{{ subnetid }}"
          tags:
            Env: "{{ Env }}"
            project: "{{ Project }}"
            Instance: "{{ item }}"
      loop: "{{ Instances }}"
      Register: Instances_output
    
    - name: Get instances output 
      ansible.builtin.debug:
        msg: "{{ Instances_output }}"



# - name: Add route53 record
#   tasks:
#         amazon.aws.route53:
#           - name: Add route35 A record for ec2 instances
#             amazon.aws.route53:
#               state: present
#               zone: "{{ zone }}"
#               record: "{{ instances }}"
#               type: A
#               ttl: 7200
#               value: 1.1.1.1,2.2.2.2,3.3.3.3
#               wait: true
  