---
- name: This Yaml is used to deploy ec2 instances in AWS
  hosts: local
  connection: local
  vars:
    action: create
    Env: dev
    Project: Roboshop
    Imageid: ami-0220d79f3f480ecf5
    Instance_type: t3.micro
    Securitygrp: devops-sg
    subnetid: subnet-0a76f340dca5f78a5
    zone: daws88s.shop
    Instances: 
       - mongodb
       - catalogue
  tasks:
    - name: Create ec2 instance
      amazon.aws.ec2_instance:
          name: "{{ item }}-{{ Env }}"
          image_id: "{{ Imageid }}"
          instance_type: "{{ Instance_type }}"
          security_group: "{{ Securitygrp }}"
          vpc_subnet_id: "{{ subnetid }}"
          tags:
            Env: "{{ Env }}"
            project: "{{ Project }}"
            Instance: "{{ item }}"
      loop: "{{ Instances }}"
      register: ec2_output


    
    # - name: Get ec2 instances output 
    #   ansible.builtin.debug:
    #     msg: "{{ ec2_output }}"



    - name: Add route53 record with Private IP address
      amazon.aws.route53:
          state: present
          zone: "{{ zone }}"
          record: "{{ item.item }}-{{ Env }}.{{ zone }}"
          type: A
          ttl: 1
          value: "{{ item.instances[0].private_ip_address }}"
          wait: true
      loop: "{{ ec2_output.results }}"
      when: item.item != 'frontend'

    - name: Add route53 record with Public IP address
      amazon.aws.route53:
          state: present
          zone: "{{ zone }}"
          record: "{{ item.item }}-{{ Env }}.{{ zone }}"
          type: A
          ttl: 1
          value: "{{ item.instances[0].public_ip_address }}"
          wait: true
          overwrite: true
      loop: "{{ ec2_output.results }}"
      when: item.item =='frontend'

    - name: Terminate ec2 instance when action is destroy
      hosts: local
      connection: local
      amazon.aws.ec2_instance:
          name: "{{ item }}-{{ Env }}"
          state: absent 
      loop : "{{ Instances }}"
      when: action == destroy